name: pg_data_etl
channels:
  - conda-forge
dependencies:
  - python=3.8*
  - flake8
  - ipython
  - jupyterlab
  - python-dotenv
  - black
  - pytest
  - psycopg2
  - pip
  - pip:
      - --editable .
